from pathlib import Path

SEED = 2
TEST_SIZE = 0.20
VALIDATION_SIZE_WITHIN_TRAIN = 0.20

BATCH_SIZE = 8
EPOCHS = 150
LEARNING_RATE = 2e-3
WEIGHT_DECAY = 1e-5
EARLY_STOPPING_PATIENCE = 20

NOUN_DIM = 4
SENTENCE_DIM = 4
MAX_ORDER = 2

CLASSIFIER_HIDDEN_DIM = 16
CLASSIFIER_DROPOUT = 0.0

DATA_PATH = Path("data/processed/MC1.txt")
OUTPUT_DIR = Path("outputs/mc1_spider")
LOG_DIR = OUTPUT_DIR / "training_logs"